### ISSUE TITLE
ZF shows as 41-46

### ISSUE THREAD

**Issue by McHIldinger** [Hoizame/AtlasLootClassic#49]
When looking at the 'Select Subcategory' dropdown, ZF shows as between 42-46, only a span of 4 levels; the end boss is a 48 or a 49, this should likely be 42-56 instead.

**Comment by chkmyid** [comment]
I don't know if it's a reference, but the database site I know, it says 44-54 levels at 'wowhead.com', 44-49 levels at 'icy-veins.com' and 43-50 levels at 'classicdb.ch'. 
Monsters are recorded at a low of 43 to a high of 48 levels. If you average the three sites, it's about 43-51 levels.
The level of players who can enter the dungeon is 35 levels, and it is recorded in Korea as a dungeon of 40 to 50 levels.
Since many famous sites are different, it will be difficult to specify the level of dungeon based on what criteria.
If I make one criterion, I think it's going to be the lowest and the highest level of the monster we talked about earlier.
Personally, I think it would be better to let you know that there is a monster at level 43-48. Of course other dungeons should have the same standards. ;-)

**Comment by McHIldinger** [comment]
I personally would rather see the low/high level of the bosses, but consistency would be best.  But that's a bigger question; this is more for the type of '46' instead of likely '56' located at 
https://github.com/Hoizame/AtlasLootClassic/blob/master/AtlasLootClassic_DungeonsAndRaids/data.lua#L1967

**Comment by Hoizame** [comment]
Hey maybe the lowestLvl-highestLvl is a good way.
Right now I cant remember how I set the dungeon levels :D

**Comment by Road-block** [comment]
Just use the meeting stone, innkeeper level data that is consistent with the game data.

[Instances by level)](https://wow.gamepedia.com/index.php?title=Instances_by_level&oldid=208471)

If you want to provide alternate (as an option) this might also be of use (tailored more towards dungeon exp)
[Dungeons by min/max npc levels](https://www.reddit.com/r/classicwow/comments/d1tkrr/all_dungeons_by_minmax_mob_level_for_best_exp/)

Finally a useful metric (that usually tracks with the meeting-stone and innkeeper dialog) is level at which the lowest dungeon quest becomes available and level at which the highest dungeon quest becomes available.

That said I would simply go with the game data as baseline (meeting stone / innkeeper dialog)
