### ISSUE TITLE
Gaea's Embrace

### ISSUE THREAD

**Issue by zaffinger** [Hoizame/AtlasLootClassic#76]
Module: Crafting
Category: Tailoring
Loottable: Armor - Back
Items: Gaea's Embrace

The item was added with patch 1.11 that should be phase 6 - but I am NOT certain about it. But the pattern is marked as phase 5.

There is definitely something off.

**Comment by zaffinger** [comment]
Every source I can find says phase 5.

**Comment by wallrik** [comment]
I guess we can only speculate what Blizzard will do... But I would assume that they won't add any of these Cenarion Circle (craftable nature resistance) items with AQ40, since it would make it a lot easier than it was back in the day.

If you were looking for a source that doesn't say phase 5:
https://classic.wowhead.com/item=22660/gaeas-embrace 
> Added in content phase 6

**Comment by Hoizame** [comment]
Hmm I will take a look at my phase data and check that

**Comment by wallrik** [comment]
Confirmed phase 6.
https://us.forums.blizzard.com/en/wow/t/seriously-though-some-clarity-about-cc-nr-craftables/569232/3

**Comment by Djfe** [comment]
I was about to open a new issue for this:
Pls update the cenarion hold items, there are lots, that will only be available in P6.
See the link @wallrik posted.
Thank you :)
